apiVersion: v1
kind: Service
metadata:
  name: NAME 
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: NAME
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: NAME
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: NAME 
    spec:
      containers:
      - name: NAME 
        image: IMAGE
        imagePullPolicy: Always 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000
