{{ if and .Values.persistence.enabled (not .Values.dataVolume.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-claim
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ## disable dynamic provisioning
  storageClassName: ""

  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.dataVolume.size | quote }}
{{- end }}
